theme: jekyll-theme-slate
Theme: jekyll-theme-slate
Theme: jekyll-theme-slate_gmright,org
Theme: jekyll-theme-files-open: "c:\program\gmright desktop\in_gmrightbrowser-IP\
Theme: jekyll_theme-be_able_to-handle-the-strugle-stuggling-check-files\correct_files\pass\files(x83)
Theme: jekyll-theme-gmright_setting_theme-jekyll(com.gmright.app)
