steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.4'

- script: |
    ruby -v
    ridk version
  displayName: 'ruby -v + ridk version'

- script: |
    mkdir tmp
    cd tmp
    mkdir home
  displayName: 'work around readline crash (for https://github.com/bundler/bundler/issues/6902)'

- script: |
    bash .azure-pipelines\patch_readline.sh
  displayName: 'patch local readline implementation (for https://github.com/bundler/bundler/issues/6907)'

- script: |
    ruby bin/rake spec:deps
  displayName: 'ruby bin/rake spec:deps'

- script: |
    ruby bin/rspec || exit 0
  displayName: 'ruby bin/rspec'
