steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  condition: not(eq(variables['Agent.OS'], 'Darwin')) # not possible on Mac

  
- script: |
    gem uninstall rake
  displayName: 'remove rake (Windows only)'
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- script: |
    ruby bin/rake spec:deps
  displayName: 'ruby bin/rake spec:deps'

- script: |
    ruby bin/rake spec
  displayName: 'ruby bin/rake spec'